name: Build Unity Project - Guess The Number

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write
  packages: write
  
jobs:
  build:
    name: Build Guess The Number
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.build_project.outputs.buildVersion }}
      output2: ${{ env.COMMIT_ID }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library-

      - name: Get commit message header
        id: get_commit_message
        run: |
          COMMIT_ID=$(git log -1 --pretty=%h)
          echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_ENV
          echo "$COMMIT_ID"
        
      - name: Build project
        id: build_project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true
          versioning: Semantic

      - name: Edit index.html
        id: edit_index_html
        run: |
            set -x
            export INDEX=$(find ./ -name index.html)
            sudo sed -i 's/width=960 height=600/width=auto height=auto/' $INDEX
            sudo sed -i 's/style="width: 960px; height: 600px;/style="width: 100%; height: 100%;/' $INDEX

      - name: Upload build artifacts
        id: upload_build_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targetPlatform }}_${{ steps.build_project.outputs.buildVersion }}_${{ env.COMMIT_ID }}
          path: build/${{ matrix.targetPlatform }}
        
  release:
    name: Release Guess The Number
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
    steps:   
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts/${{ matrix.targetPlatform }}
  
      - name: Zipping Downloaded Build
        env:
          BUILD_VERSION: ${{ needs.build.outputs.output1 }}
          BUILD_COMMIT_ID: ${{ needs.build.outputs.output2 }}
        run: |
          zip -r build-artifacts/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}.zip -9 build-artifacts/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}/${{ matrix.targetPlatform}}/
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_VERSION: ${{ needs.build.outputs.output1 }}
          BUILD_COMMIT_ID: ${{ needs.build.outputs.output2 }}
        with:
          name: GuessTheNumber_${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}
          tag_name: ${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}
          files: |
            build-artifacts/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}_${{ env.BUILD_VERSION }}_${{ env.BUILD_COMMIT_ID }}.zip
