name: Experiments

on: [workflow_dispatch] # Allows manual execution

jobs:
  test:
    name: Environment Test
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory
        run: pwd -P

      - name: Check Installed Zip Utility
        run: which zip

      - name: Display Zip Help Command
        run: zip --help

      - name: Check System Information
        run: |
          uname -a
          lsb_release -a || cat /etc/os-release
